### ISSUE TITLE
Bias-Tee in ini file?

### ISSUE THREAD

**Issue by longview** [jeroenbeijer/SDRReceiver#10]
Hi, it would be great if there was a setting in the .ini file to enable the bias-tee automatically.

I use an active amplifier near the SDR, so auto-start isn't very useful unless it also powers the bias-tee at the same time.

Also thanks for making this software, it seems to work great and is a huge improvement over using VAC and SDR# instances or similar!

**Comment by jeroenbeijer** [comment]
Closing this one
