### ISSUE TITLE
Remote RTL gain setting undocumented

### ISSUE THREAD

**Issue by longview** [jeroenbeijer/SDRReceiver#11]
Trying out the remote RTL setup I found the gain was way too low by default, and the rtl_tcp server gain had very little effect.
The parameter "remote_rtl_gain_idx" is not documented but appears to work, but I'm not sure what the units are for this?

**Comment by jeroenbeijer** [comment]
It uses the same gain index that rtl_tcp uses which you can pass there at start up. So basically the index in this list for a regular RTLSDR V3:

#valid tuner gains r82xx_gains[] = { 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496 };

 To select the highest gain the index would be 28. Thanks for pointing this, I have updated the readme.

**Comment by jeroenbeijer** [comment]
Closing this one
