### ISSUE TITLE
.ini file doesn't exist

### ISSUE THREAD

**Issue by BrunoKlu** [jeroenbeijer/SDRReceiver#12]
Hello,

Thanks for the software,
Hope you are doing well,

Here is, on the screenshot, the error message i'm getting after trying to launch SDRReciever. ("Given settings ini file doesn't exist")

The .ini files are located in the same folder as the SDRReciever.exe , I'm sure to write the good .ini filenames.... not sure where i'm going wrong.

Thanks for your help

Bruno

![Screenshot SDRReciever](https://user-images.githubusercontent.com/73705824/139830191-8f9b561e-ba93-4641-a292-7e61c090eea9.png)

**Comment by jeroenbeijer** [comment]
Hi Bruno,

Doing very well thanks, hope you are too.

From what I can see you have the ini file (sdr_25E.ini) in the same folder as the bat file that starts the sdrreceiver. But the bat file has -s ini/sdr_25E.ini. So you can either create a new folder under C:\SDRReceiver called ini and put the ini file in there, or edit the bat file and just pass the ini file as **-s sdr_25E.ini**

Good luck

Jeroen

**Comment by jeroenbeijer** [comment]
Closing
