### ISSUE TITLE
Linux Version?

### ISSUE THREAD

**Issue by catalinalb** [jeroenbeijer/SDRReceiver#14]
Would be great if I could run this on my ubuntu pi :) (dragonOS from cemaexecuter)

Thank you,
Catalin

**Comment by alphafox02** [comment]
Hi Catalinalb. I actually just put it into the build, but someone is reporting to me an issue. I may have installed it wrong or maybe there's a problem, either way I think they'll open a ticket with the details.

**Comment by thebaldgeek** [comment]
I am testing SDRReceiver on the latest build of [DragonOS ](https://sourceforge.net/projects/dragonos-pi64/) (64 bit. built Dec 5th 2021) on a 4gb Raspberry Pi 4 and get the following error:
$ SDRReceiver -v
SDRReceiver 1.0
$SDRReceiver -s 54L.ini
terminate called after throwing an instance of 'std::bad_alloc'
  what(): std::bad_alloc
/usr/local/bin/SDRReceiver: line 2: 62153 Aborted    (core dumped) /opt/SDRReceiver/bin/SDRReceiver "$@"

This is using your sample 54w ini file.

I am in touch with @alphafox02 so please let me know if there is anything I can test or check for either of you.

Thanks.

**Comment by thebaldgeek** [comment]
All.
Sorry for the noise, VNC mangled the copy paste of the ini file.
When I downloaded it via Firefox on DragonOS and used that local copy/paste, everything works as it should.
![image](https://user-images.githubusercontent.com/7385116/145060720-52a02ef2-3bfb-488c-9169-c81190c1ab2f.png)

This is very exciting to have a Raspberry Pi distro with all this working out of the box!

Thanks all.

**Comment by jeroenbeijer** [comment]
Thanks for the feeback Ben. I don't have one of these myself and not all that up to date on all of this but I believe Jonti previously mentioned the linux build script can be used on Pi.
