### ISSUE TITLE
Use SDR serial number?

### ISSUE THREAD

**Issue by thebaldgeek** [jeroenbeijer/SDRReceiver#7]
Some systems have two (or more) RTLSDRv3 attached.     
Some time back we have used `rtl_eeprom -s` to set each devices serial number. This helped the usual SDR software to use the correct device when they each started up.   
With SDRReceiver is there a way to specify the dongle serial number in the ini file?    
We'd like to use one dongle for C-Band and the other for L-Band.

**Comment by jeroenbeijer** [comment]
Not at the moment but I have thought about it and will have a look at it. You can use multiple dongles as it is right now though, I have run 3 instances without issues. So long as you dont unplug or move the devices around my experience has been that they will keep the same index number in the dropdown. Currently I have 2 dongles running on one PC for 25E and 54W and the SDRs have the autostart options with dongle indexes 0 and 1 set. Has been working well for ages with everything auto starting on reboot.

**Comment by jeroenbeijer** [comment]
finally had some time to add a few things so this is now an option, see readme for details.

**Comment by thebaldgeek** [comment]
This is fantastic. Thank-you very much.
I see in the readme that you are looking to tweak a few things for C-Band. Looking forward to that. All three of us C-Band guys (143E, 98W and 25E) have spent hours and failed to get SDRReceiver working on that band. We are all still using VAC and getting the usual BAD CRC errors.

**Comment by jeroenbeijer** [comment]
Closing this one.
