### ISSUE TITLE
Feature request - adjust each VFO frequency from GUI

### ISSUE THREAD

**Issue by thebaldgeek** [jeroenbeijer/SDRReceiver#8]
As we work with the receiver and with different user setups we are finding the individual VFOs (not the master or sub group(s)) often need a little moving.   
Not a perfect example, but here is what we are seeing:   
![sdrrselectsubvfo](https://user-images.githubusercontent.com/7385116/128365006-64d0fa80-bba3-481a-a231-b75ac260c451.png)
   
 In this case, VFO45 is just too far off frequency for Jaero to get lock.    
 We can select it from the list and see that indeed, its out a bit.    
 What would be extremely helpful is if when you selected that VFO from the list, it showed its frequency, which you can then jog it up or down as needed and then simply copy paste that new adjusted frequency into your ini file for that VFO.    
     
    
![sdrrvfooffset](https://user-images.githubusercontent.com/7385116/128365332-42cb5333-5fe3-47d6-8737-33fe60ea2e15.png)
   
 Once SDRReceiver is restarted, that VFO will be on the correct frequency for your SDR.    
 As it stands now, if you select a sub-VFO from the list, the master VFO is offset and this moves ALL VFOs up or down, sometimes requiring all Jaeros to be re-locked.    
     
 We are tying to use 'standard' ini files for each satellite, but the subtle differences between everyone's SDR is surprising.

**Comment by jeroenbeijer** [comment]
I see what you are saying. As it is now you can "move" all VFO's up and down by either using the mix_offset key in the ini file or by changing the main center_frequency. You can use the up and down arrows next to the tuner center frequency in the gui to tune up or down on the fly which should tell you how far off the VFO is. I would expect all VFO's would be off more or less by an equal number of Hz from the dongle that was used to generate the ini file. Maybe if you leave a little more "wiggle" room in the template so to speak (so they are not right on the edge of the jaero spectrum) it would be sufficient to nudge all VFO's on a different dongle by X number of Hz to make them line up with jaero nicely?

**Comment by thebaldgeek** [comment]
Thanks for the feedback.    
For L-Band the more we dial in the .ini file, (ie get a better average for each of the VFO frequencies) the smoother each station setup is.
